### ISSUE TITLE
Pending deprecation of `imp`

### ISSUE THREAD

**Issue by JSKenyon** [mattyowl/astLib#5]
`astLib` produces the following warning: 

```
/venvs/cdenv/lib/python3.10/site-packages/PyWCSTools/wcs.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
```

Python 3.12 is only slated for release later this year so this change isn't urgent.

**Comment by mattyowl** [comment]
Thanks for the heads up. I hope this will just be a case of updating the wrapping with swig.

Cheers
Matt

**Comment by mattyowl** [comment]
I've made a new release that's now on PyPI (v0.11.9) - hopefully this should fix this issue.

**Comment by JSKenyon** [comment]
Awesome! Will let you know if it ever comes up again.
